class Roles:

    nfl = [
        "Arizona Cardinals",
        "Atlanta Falcons",
        "Baltimore Ravens",
        "Buffalo Bills",
        "Carolina Panthers",
        "Chicago Bears",
        "Cincinnati Bengals",
        "Cleveland Browns",
        "Dallas Cowboys",
        "Denver Broncos",
        "Detroit Lions",
        "Green Bay Packers",
        "Houston Texans",
        "Indianapolis Colts",
        "Jacksonville Jaguars",
        "Kansas City Chiefs",
        "Las Vegas Raiders",
        "Los Angeles Chargers",
        "Los Angeles Rams",
        "Miami Dolphins",
        "Minnesota Vikings",
        "New England Patriots",
        "New Orleans Saints",
        "New York Giants",
        "New York Jets",
        "Philadelphia Eagles",
        "Pittsburgh Steelers",
        "San Francisco 49ers",
        "Seattle Seahawks",
        "Tampa Bay Buccaneers",
        "Tennessee Titans",
        "Washington Commanders",
    ]

    nfl_logos = [
        "AFC",
        "AFC Championship",
        "Draft",
        "Hall Of Fame",
        "NFC",
        "NFC Championship",
        "NFL",
        "Pro Bowl",
        "Super Bowl",
    ]
  
    nba = [
        "Atlanta Hawks",
        "Boston Celtics",
        "Brooklyn Nets",
        "Charlotte Bobcats",
        "Chicago Bulls",
        "Cleveland Cavaliers",
        "Dallas Mavericks",
        "Denver Nuggets",
        "Detroit Pistons",
        "Golden State Warriors",
        "Houston Rockets",
        "Indiana Pacers",
        "Los Angeles Clippers",
        "Los Angeles Lakers",
        "Memphis Grizzlies",
        "Miami Heat",
        "Milwaukee Bucks",
        "Minnesota Timberwolves",
        "New Orleans Hornets",
        "New York Knicks",
        "Oklahoma City Thunder",
        "Orlando Magic",
        "Philadelphia Sixers",
        "Phoenix Suns",
        "Portland Trail Blazers",
        "Sacramento Kings",
        "San Antonio Spurs",
        "Toronto Raptors",
        "Utah Jazz",
        "Washington Wizards",
    ]

    nba_logos = [
        "All Star",
        "Draft",
        "Eastern Conference",
        "Finals Trophy",
        "NBA",
        "Playoffs",
        "Western Conference",
    ]
    
    mlb = [
        "Atlanta Braves",
        "Miami Marlins",
        "New York Mets",
        "Philadelphia Phillies",
        "Washington Nationals",
        "Chicago Cubs",
        "Cincinnati Reds",
        "Milwaukee Brewers",
        "Pittsburgh Pirates",
        "St. Louis Cardinals",
        "Arizona Diamondbacks",
        "Colorado Rockies",
        "Los Angeles Dodgers",
        "San Diego Padres",
        "San Francisco Giants",
        "Baltimore Orioles",
        "Boston Red Sox",
        "New York Yankees",
        "Tampa Bay Rays",
        "Toronto Blue Jays",
        "Chicago White Sox",
        "Cleveland Indians",
        "Detroit Tigers",
        "Kansas City Royals",
        "Minnesota Twins",
        "Houston Astros",
        "Los Angeles Angels",
        "Oakland Athletics",
        "Seattle Mariners",
        "Texas Rangers",
    ]

    mlb_logos = [
        "ALDS",
        "American League",
        "MLB",
        "MLB Network",
        "National League",
        "NLDS",
        "World Series",
    ]
    
    nhl = [
        "Anaheim Ducks",
        "Arizona Coyotes",
        "Boston Bruins",
        "Buffalo Sabres",
        "Calgary Flames",
        "Carolina Hurricanes",
        "Chicago Blackhawks",
        "Colorado Avalanche",
        "Columbus Blue Jackets",
        "Dallas Stars",
        "Detroit Red Wings",
        "Edmonton Oilers",
        "Florida Panthers",
        "Los Angeles Kings",
        "Minnesota Wild",
        "Montreal Canadiens",
        "Nashville Predators",
        "New Jersey Devils",
        "New York Islanders",
        "New York Rangers",
        "Ottawa Senators",
        "Philadelphia Flyers",
        "Pittsburgh Penguins",
        "San Jose Sharks",
        "Seattle Kraken",
        "St. Louis Blues",
        "Tampa Bay Lightning",
        "Toronto Maple Leafs",
        "Vancouver Canucks",
        "Vegas Golden Knights",
        "Washington Capitals",
        "Winnipeg Jets",
    ]
    
    nhl_logos = [
        "AllStar",
        "Eastern Conference",
        "NHL",
        "NHL Playoffs",
        "Stanley Cup Finals",
        "West Conference",
        "Winner Classic",
    ]
  
    soccer = [
        "Atlanta United FC",
        "Chicago Fire FC",
        "Colorado Rapids",
        "Columbus Crew SC",
        "D.C. United",
        "FC Cincinnati",
        "FC Dallas",
        "Houston Dynamo",
        "Inter Miami CF",
        "LA Galaxy",
        "Los Angeles Football Club",
        "Minnesota United FC",
        "Montreal Impact",
        "Nashville SC",
        "New England Revolution",
        "New York City FC",
        "New York Red Bulls",
        "Orlando City SC",
        "Philadelphia Union",
        "Portland Timbers",
        "Real Salt Lake",
        "San Jose Earthquakes",
        "Seattle Sounders FC",
        "Sporting Kansas City",
        "Toronto FC",
        "Vancouver Whitecaps FC",
    ]
    
    fcf = [
        "8oki",
        "Beasts",
        "Bored Ape FC",
        "Glacier Boyz",
        "Kingpins",
        "Knights Of Degen",
        "Shoulda Been Stars",
        "Zappers",
    ]
      
    usfl = [
        "Birmingham Stallions",
        "Houston Gamblers",
        "Michigan Panthers",
        "New Jersey Generals",
        "New Orleans Breakers",
        "Philadelphia Stars",
        "Pittsburgh Maulers",
        "Tampa Bay Bandits",
    ]
      
    xfl = [
        "Arlington Renegades",
        "DC Defenders",
        "Houston Roughnecks",
        "Orlando Guardians",
        "San Antonio Brahmas",
        "Seattle Sea Dragons",
        "St Louis Battlehawks",
        "Vegas Vipers",
    ]

    football_fusion = [
        "Arizona Heat",
        "Atlanta Nighthawks",
        "Baltimore Royals",
        "Buffalo Boars",
        "Carolina Predators",
        "Chicago Bucks",
        "Cincinnati Tigers",
        "Cleveland Braves",
        "Dallas Outlaws",
        "Denver Mustangs",
        "Detroit Lightning",
        "Green Bay Paladins",
        "Houston Drillers",
        "Indianapolis Cubs",
        "Jacksonville Devils",
        "Kansas City Cherokees",
        "Los Angeles Comets",
        "Los Angeles Rage",
        "Miami Sharks",
        "Minnesota Vipers",
        "New England Nationals",
        "New Orleans Knights",
        "New York Greats",
        "New York Juggernauts",
        "Las Vegas Renegades",
        "Philadelphia Raptors",
        "Pittsburgh Stormers",
        "San Francisco Lions",
        "Seattle Cyclones",
        "Tampa Bay Pirates",
        "Tennessee Trojans",
        "Washington Warriors",
    ]

    ultimate_football = [
        "Alabama Black Bears",
        "Arizona Firebirds",
        "Atlantis Tridents",
        "Barton Bruisers",
        "Birmingham Bluebirds",
        "Canton Bulldogs",
        "Charlotte Monarchs",
        "Colorado Blizzards",
        "Dallas Dragons",
        "Honolulu Volcanoes",
        "Houston Hornets",
        "Korblox Kobras",
        "Las Vegas Jackpots",
        "Los Angeles Tigers",
        "Lua Lions",
        "Mexico City Aztecs",
        "Miami Sunshine",
        "Minnesota Huskies",
        "Nashville Nightmares",
        "Nevada Miners",
        "New England Musketeers",
        "New York Knights",
        "Oklahoma Storm Chasers",
        "Orlando Lightning",
        "Pemberely Punishers",
        "Philadelphia Liberties",
        "Roblox Warriors",
        "Salt Lake City Stallions",
        "San Diego Cruisers",
        "San Francisco Comets",
        "Santa Fe Outlaws",
        "Seattle Evergreens",
    ]
  
    soccer = [
        "AFC Bournemouth",
        "Arsenal FC",
        "Aston Villa FC",
        "Brentford FC",
        "Brighton Hove Albion FC",
        "Chelsea FC",
        "Crystal Palace FC",
        "Everton FC",
        "Fulham FC",
        "Leeds United FC",
        "Leicester City FC",
        "Liverpool FC",
        "Manchester City FC",
        "Manchester United FC",
        "Newcastle United FC",
        "Nottingham Forest FC",
        "Southampton FC",
        "Tottenham Hotspur FC",
        "West Ham United FC",
        "Wolverhampton Wanderers FC",      
    ]
  
    college_OLD = [
        "Alabama Crimson Tide",
        "Auburn Tigers",
        "Boston College Eagles",
        "Buffalo Bulls",
        "Cincinnati Bearcats",
        "Clemson Tigers",
        "Colorado Buffaloes",
        "Georgia Bulldogs",
        "Indiana Hoosiers",
        "Iowa Hawkeyes",
        "Kansas Jayhawks",
        "Maryland Terrapins",
        "Miami Hurricanes",
        "Michigan State Spartans",
        "Michigan Wolverines",
        "Nebraska Cornhuskers",
        "North Carolina Tar Heels",
        "Notre Dame",
        "Ohio State Buckeyes",
        "Oklahoma Sooners",
        "Oregon Ducks",
        "Penn State Nittany Lions",
        "Pittsburgh Panthers",
        "Rutgers Scarlet Knights",
        "Stanford Cardinal",
        "Tennessee Volunteers",
        "Texas Longhorns",
        "USC Trojans",
        "Utah Utes",
        "Virginia Tech:",
        "West Virginia Mountaineers",
        "Wisconsin Badgers",
    ]

    college = [
        "Boston College Eagles",
        "Clemson Tigers",
        "Duke Blue Devils",
        "Florida State Seminoles",
        "Georgia Tech Yellow Jackets",
        "Louisville Cardinals",
        "Miami Hurricanes",
        "NC State Wolfpack",
        "North Carolina Tar Heels",
        "Pittsburgh Panthers",
        "Syracuse Orange",
        "Virginia Cavaliers",
        "Virginia Tech",
        "Wake Forest Demon Deacons",    
        "Illinois Fighting Illini",
        "Indiana Hoosiers",
        "Iowa Hawkeyes",
        "Maryland Terrapins",
        "Michigan State Spartans",
        "Michigan Wolverines",
        "Minnesota Golden Gophers",
        "Nebraska Cornhuskers",
        "Northwestern Wildcats",
        "Ohio State Buckeyes",
        "Penn State Nittany Lions",
        "Purdue Boilermakers",
        "Rutgers Scarlet Knights",
        "UCLA Bruins",
        "USC Trojans",
        "Wisconsin Badgers",
        "Baylor Bears",
        "Iowa State Cyclones",
        "Kansas Jayhawks",
        "Kansas State Wildcats",
        "Oklahoma State Cowboys",
        "TCU Horned Frogs",
        "Texas Tech Red Raiders",
        "West Virginia Mountaineers",
        "Alabama Crimson Tide",
        "Arkansas Razorbacks",
        "Auburn Tigers",
        "Florida Gators",
        "Georgia Bulldogs",
        "Kentucky Wildcats",
        "LSU Tigers",
        "Mississippi State Bulldogs",
        "Missouri Tigers",
        "Oklahoma Sooners",
        "Ole Miss Rebels",
        "South Carolina Gamecocks",
        "Tennessee Volunteers",
        "Texas AM Aggies",
        "Texas Longhorns",
        "Vanderbilt Commodores",
        "Boise State Broncos",
        "BYU Cougars",
        "Cincinnati Bearcats",
        "Coastal Carolina Chanticleers",
        "Colorado State Rams",
        "Hawaii Rainbow Warriors",
        "Houston Cougars",
        "Notre Dame Fighting Irish",
        "San Diego State Aztecs",
        "San Jose State Spartans",
        "South Florida Bulls",
        "Troy Trojans",
        "Tulane Green Wave",
        "UCF Knights",
        "UConn Huskies",
        "Wyoming Cowboys",     
    ]
  
    college_acc = [
        "Boston College Eagles",
        "Clemson Tigers",
        "Duke Blue Devils",
        "Florida State Seminoles",
        "Georgia Tech Yellow Jackets",
        "Louisville Cardinals",
        "Miami Hurricanes",
        "NC State Wolfpack",
        "North Carolina Tar Heels",
        "Pittsburgh Panthers",
        "Syracuse Orange",
        "Virginia Cavaliers",
        "Virginia Tech",
        "Wake Forest Demon Deacons",
    ]

    college_big_10 = [
        "Illinois Fighting Illini",
        "Indiana Hoosiers",
        "Iowa Hawkeyes",
        "Maryland Terrapins",
        "Michigan State Spartans",
        "Michigan Wolverines",
        "Minnesota Golden Gophers",
        "Nebraska Cornhuskers",
        "Northwestern Wildcats",
        "Ohio State Buckeyes",
        "Penn State Nittany Lions",
        "Purdue Boilermakers",
        "Rutgers Scarlet Knights",
        "UCLA Bruins",
        "USC Trojans",
        "Wisconsin Badgers",
    ]

    college_big_12 = [
        "Baylor Bears",
        "Iowa State Cyclones",
        "Kansas Jayhawks",
        "Kansas State Wildcats",
        "Oklahoma State Cowboys",
        "TCU Horned Frogs",
        "Texas Tech Red Raiders",
        "West Virginia Mountaineers",
    ]

    college_pac_12 = [
        "Arizona State Sun Devils",
        "Arizona Wildcats",
        "California Golden Bears",
        "Colorado Buffaloes",
        "Oregon Ducks",
        "Oregon State Beavers",
        "Stanford Cardinal",
        "Utah Utes",
        "Washington State Cougars",
    ]

    college_sec = [
        "Alabama Crimson Tide",
        "Arkansas Razorbacks",
        "Auburn Tigers",
        "Florida Gators",
        "Georgia Bulldogs",
        "Kentucky Wildcats",
        "LSU Tigers",
        "Mississippi State Bulldogs",
        "Missouri Tigers",
        "Oklahoma Sooners",
        "Ole Miss Rebels",
        "South Carolina Gamecocks",
        "Tennessee Volunteers",
        "Texas AM Aggies",
        "Texas Longhorns",
        "Vanderbilt Commodores",
    ]

    college_more_pack = [
        "Boise State Broncos",
        "BYU Cougars",
        "Cincinnati Bearcats",
        "Coastal Carolina Chanticleers",
        "Colorado State Rams",
        "Hawaii Rainbow Warriors",
        "Houston Cougars",
        "Notre Dame Fighting Irish",
        "San Diego State Aztecs",
        "San Jose State Spartans",
        "South Florida Bulls",
        "Troy Trojans",
        "Tulane Green Wave",
        "UCF Knights",
        "UConn Huskies",
        "Wyoming Cowboys",
    ]
  
    college_bowls = [
        "CFP",
        "Cotton Bowl",
        "Fiesta Bowl",
        "National Championship Trophy",
        "Orange Bowl",
        "Peach Bowl",
        "Rose Bowl",
        "Sugar Bowl",     
    ]

    college_conferences = [
        "American Athletic Conference",
        "Atlantic Coast Conference",
        "Big 12 Conference",
        "Big Ten Conference",
        "Conference USA",
        "FBS Independents",
        "Mid American Conference",
        "Mountain West Conference",
        "NCAA",
        "Pac 12",
        "Southeastern Conference",
        "Sun Belt Conference",    
    ]

    general_symbols = [
        "Info",
        "Inquiry",
        "Prohibited",
        "Warn",
    ]
    
    general_symbols_neon = [
        "Info",
        "Inquiry",
        "Prohibited",
        "Warn",
    ]
    
    social_media = [
        "Check_Mark",
        "X_Mark",
        "Heart",
        "Retweet",
        "Tweet",
        "Roblox",
        "Youtube",
        "Twitch",
        "Tiktok",
        "Verizon",
        "Tostitos",
        "NBC",
        "Intel",
        "Fox",
        "ESPN",
        "CBS",
    ]
    
    devtraits = [
        "Hidden Dev trait",
        "Normal Dev trait",
        "Star Dev trait",
        "Super Star Dev Trait",
        "Super Star X Factor",
    ]

    numbers = [
        "Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine"    
    ]

    deparments = [
        "Commissioner",
        "Design",
        "Film",
        "Justice",
        "Media",
        "Moderator",
        "Operations",
        "Statistics",      
    ]

    divisions = [
        "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8"
    ]

    rings = [
       "1x_Ring", "2x_Ring", "3x_Ring", "4x_Ring", "5x_Ring", "6x_Ring"  
    ]


    stars = [
        "Star", "Super_Star", "Pro", "Elite", "Legend", "Hall_Of_Fame"
    ]